packages:
  - 'apps/backend'
  - 'apps/web'
  - 'apps/mobile'
  - 'packages/eslint-config'
  - 'packages/prettier-config'
  - 'packages/types'

# Catalog for shared dependencies to ensure version consistency
catalog:
  # Runtime dependencies
  '@nestjs/common': ^10.0.0
  '@nestjs/core': ^10.0.0
  '@nestjs/platform-express': ^10.0.0
  'typescript': ^5.5.4
  'react': ^18.2.0
  'react-dom': ^18.2.0
  'next': ^14.0.0

  # Development dependencies
  '@types/node': ^20.14.10
  '@typescript-eslint/eslint-plugin': ^6.0.0
  '@typescript-eslint/parser': ^6.0.0
  'eslint': ^8.57.0
  'prettier': ^3.0.0
  'jest': ^29.7.0
  'ts-jest': ^29.1.2
