#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run linting
npm run lint

# Run type checking
npm run type-check

# Run tests
npm run test -- --watchAll=false --passWithNoTests

# Run security audit
npm run security:audit
